#! /bin/bash

runNumber=${1}
settingsFile=${2}
outputFolder=${3}
configFile=${4}
excludedPlane=${5}

currentFolder=`pwd`
echo "Aligning planes" >> ${outputFolder}/analysis.log
res=64.38
$EUTELESCOPE/jobsub/jobsub.py --option DatabasePath=${outputFolder}/database \
			      --option HistogramPath=${outputFolder}/histogram \
			      --option LcioPath=${outputFolder}/lcio \
			      --option LogPath=${outputFolder}/logs \
			      --option ResolutionX="$res $res $res $res $res $res $res" \
			      --option ResolutionY="$res $res $res $res $res $res $res" \
			      --option ExcludePlanes="${excludedPlane}"  \
			      --config=${configFile} -csv ${settingsFile} align ${runNumber}
cd ${outputFolder}/logs/
rm *.log *.xml 
zipname=`printf align-"%06d".zip ${runNumber}`
unzip $zipname
name=`printf align-"%06d".log ${runNumber}`
echo "  Original resolution: " $res >> ${outputFolder}/analysis.log
if grep "multiply all input standard deviations by factor" $name
then
  factor=`cat $name |  sed -n -e "s/^.*multiply all input standard deviations by factor//p" | bc -l`
  echo "  Recalculating resolution with factor: " $factor >> ${outputFolder}/analysis.log
  res=`echo "$res*$factor" | bc -l`
  echo "  New resolution: " $res >> ${outputFolder}/analysis.log
  rm *.log *.xml 
  cd $currentFolder
  $EUTELESCOPE/jobsub/jobsub.py --option DatabasePath=${outputFolder}/database \
				--option HistogramPath=${outputFolder}/histogram \
				--option LcioPath=${outputFolder}/lcio \
				--option LogPath=${outputFolder}/logs \
				--option ResolutionX="$res $res $res $res $res $res $res" \
				--option ResolutionY="$res $res $res $res $res $res $res" \
				--option ExcludePlanes="${excludedPlane}" \
				--config=${configFile} -csv ${settingsFile} align ${runNumber}
else
  rm *.log *.xml 
  echo "  Resolution was fine" >> ${outputFolder}/analysis.log
fi
cd ${outputFolder}/logs
unzip $zipname
if grep "Number of tracks used:" $name
then
  nTracks=`cat $name |  sed -n -e "s/^.*Number of tracks used://p" | bc -l`
  if (($nTracks<100))
  then
    echo "  Alignment step failed," $nTracks "tracks found for alignment in run" ${runNumber} >> ${outputFolder}/../analysis.log
    echo "  Alignment step failed," $nTracks "tracks found for alignment" >> ${outputFolder}/analysis.log
    exit 1
  else
    echo "  Alignment worked fine," $nTracks "tracks found for alignment" >> ${outputFolder}/analysis.log
  fi
else
  echo "  Alignment step failed, output is strange in run" ${runNumber} >> ${outputFolder}/../analysis.log
  echo "  Alignment step failed, output is strange" >> ${outputFolder}/analysis.log
  exit 1
fi
rm *.log *.xml
cd $currentFolder
